version: '3.8'

services:
  db:
    image: postgres:16
    container_name: world_history_db
    environment:
      POSTGRES_USER: world_history_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: world_history_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
